name: Release

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/obviyus/gotm-remix:${{ github.sha }}
            ghcr.io/obviyus/gotm-remix:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            id=TURSO_DATABASE_URL,env=TURSO_DATABASE_URL
            id=TURSO_AUTH_TOKEN,env=TURSO_AUTH_TOKEN
